dubbo:
  application:
    name: springboot-dubbo-client
  registry: #地址
    address: 192.168.43.201:2181
    protocol: zookeeper
  consumer: #消费方
    timeout: 3000
    check: false
server:
  port: 8010